// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaRfSrIeH6VW2WA7PyFRuMyPzmT2_H_hY',
    appId: '1:491223416451:web:bd84b0e1304add4f9225b6',
    messagingSenderId: '491223416451',
    projectId: 'meassageapp-dc3cb',
    authDomain: 'meassageapp-dc3cb.firebaseapp.com',
    storageBucket: 'meassageapp-dc3cb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ4Sa0l8gnfx2sWpJeVTiXwsfPJwOC74A',
    appId: '1:491223416451:android:5bcca80133953f879225b6',
    messagingSenderId: '491223416451',
    projectId: 'meassageapp-dc3cb',
    storageBucket: 'meassageapp-dc3cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBNAel7PvEXjUs0zE0ceKyfKthVyVAkpo',
    appId: '1:491223416451:ios:a3cea9f08383871e9225b6',
    messagingSenderId: '491223416451',
    projectId: 'meassageapp-dc3cb',
    storageBucket: 'meassageapp-dc3cb.firebasestorage.app',
    iosBundleId: 'com.example.meassageApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBNAel7PvEXjUs0zE0ceKyfKthVyVAkpo',
    appId: '1:491223416451:ios:a3cea9f08383871e9225b6',
    messagingSenderId: '491223416451',
    projectId: 'meassageapp-dc3cb',
    storageBucket: 'meassageapp-dc3cb.firebasestorage.app',
    iosBundleId: 'com.example.meassageApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaRfSrIeH6VW2WA7PyFRuMyPzmT2_H_hY',
    appId: '1:491223416451:web:2cb3c1a6a9be8be59225b6',
    messagingSenderId: '491223416451',
    projectId: 'meassageapp-dc3cb',
    authDomain: 'meassageapp-dc3cb.firebaseapp.com',
    storageBucket: 'meassageapp-dc3cb.firebasestorage.app',
  );
}
